name: Update Database from Google Sheets
on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  run-update-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"


      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install gspread pandas sqlalchemy oauth2client

      - name: Set up Google Sheets Credentials
        # 這是最重要的一步，確保你的憑證檔案安全
        run: echo '${{ secrets.GOOGLE_CREDENTIALS }}' > smart-planting-468806-f5b899621000.json
        
      - name: Run Python script

        run: python update.py

      - name: Commit and Push changes
        run: |
          # 檢查是否有檔案變動（例如 .db 檔案被更新）
          if git diff --exit-code plant_data.db; then
            echo "No changes to commit. Exiting."
          else
            git add plant_data.db
            git commit -m "Automated update: new data from Google Sheets"
            git push
            echo "Successfully pushed updated database."
          fi